import React from 'react'
import './ResultSection.css'

/**
 * ResultSection
 *
 * Layout:
 *   ┌─────────────────────────────────────────────────────┐
 *   │  Response   Test Cases Generated   [↓ Download JSON]│
 *   ├─────────────────────────────────────────────────────┤
 *   │  API Summary                                        │
 *   ├────────────────┬────────────────┬───────────────────┤
 *   │ Positive Tests │ Negative Tests │ Validation Tests  │
 *   ├─────────────────────────────────────────────────────┤
 *   │  Expected HTTP Responses                            │
 *   └─────────────────────────────────────────────────────┘
 *
 * Download format: .json  (includes full API context + request body per test)
 *
 * Props:
 *   data        TestCaseResponse from backend
 *   requestInfo { method, endpoint, description, requestBody }
 */
function ResultSection({ data, requestInfo }) {
  if (!data) return null

  /* ── JSON Download ─────────────────────────────────────────── */
  const handleDownload = () => {
    // Parse requestBody string into an object if it's valid JSON, else keep as string
    let parsedBody = requestInfo.requestBody || null
    if (parsedBody) {
      try { parsedBody = JSON.parse(parsedBody) } catch { /* keep as string */ }
    }

    // Helper: enrich each test case with its own AI-generated requestBody.
    // The AI now generates a unique requestBody per test case that matches the scenario.
    // Falls back to the global API request body only when the test has none.
    const enrichTests = (tests) =>
      (tests || []).map((t) => ({
        title:          t.title,
        description:    t.description,
        expectedStatus: t.expectedStatus,
        // Use the per-test requestBody generated by AI; fall back to global API body if absent
        requestBody:    (t.requestBody !== undefined && t.requestBody !== null)
                          ? t.requestBody
                          : (parsedBody ?? 'N/A (no request body)'),
      }))

    const payload = {
      tool:        'TestPilot AI',
      generatedAt: new Date().toISOString(),
      api: {
        method:      requestInfo.method?.toUpperCase(),
        endpoint:    requestInfo.endpoint,
        description: requestInfo.description,
        requestBody: parsedBody ?? null,
      },
      summary: data.summary,
      testCases: {
        positive:   enrichTests(data.positiveTests),
        negative:   enrichTests(data.negativeTests),
        validation: enrichTests(data.validationTests),
      },
      expectedResponses: data.expectedResponses || [],
    }

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' })
    const url  = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href     = url
    link.download = 'TestCases.json'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  /* ── Render ────────────────────────────────────────────────── */
  return (
    <div className="result-panel">

      {/* ── Response Header Bar ─────────────────────────────── */}
      <div className="result-header">
        <div className="result-header-left">
          <span className="response-label">Response</span>
          <span className="result-status-dot" aria-hidden="true"></span>
          <span className="result-status-text">Test Cases Generated</span>
        </div>
        <button
          id="download-btn"
          className="download-btn"
          onClick={handleDownload}
          title="Download all test cases as JSON"
        >
          <span aria-hidden="true">↓</span>
          Download TestCases.json
        </button>
      </div>

      {/* ── API Summary ─────────────────────────────────────── */}
      <div className="result-section summary-section">
        <div className="section-label">
          <span className="section-label-icon" aria-hidden="true">◈</span>
          API Summary
        </div>
        <p className="summary-text">{data.summary}</p>
      </div>

      {/* ── 3-Column Test Case Grid ──────────────────────────── */}
      <div className="test-grid">
        <TestColumn
          title="Positive Tests"
          badge="badge-positive"
          headerClass="col-positive"
          tests={data.positiveTests}
        />
        <TestColumn
          title="Negative Tests"
          badge="badge-negative"
          headerClass="col-negative"
          tests={data.negativeTests}
        />
        <TestColumn
          title="Validation Tests"
          badge="badge-validation"
          headerClass="col-validation"
          tests={data.validationTests}
        />
      </div>

      {/* ── Expected HTTP Responses ──────────────────────────── */}
      <div className="result-section">
        <div className="section-label">
          <span className="section-label-icon" aria-hidden="true">⇄</span>
          Expected HTTP Responses
          <span className="section-count">{data.expectedResponses?.length || 0}</span>
        </div>
        <div className="responses-table">
          {data.expectedResponses && data.expectedResponses.length > 0 ? (
            data.expectedResponses.map((r, i) => (
              <div key={i} className="response-row">
                <span className={`status-chip ${getStatusClass(r.status)}`}>{r.status}</span>
                <span className="response-msg">{r.message}</span>
              </div>
            ))
          ) : (
            <p className="empty-msg">No expected responses listed.</p>
          )}
        </div>
      </div>

    </div>
  )
}

/* ── TestColumn sub-component ─────────────────────────────────── */
function TestColumn({ title, badge, headerClass, tests }) {
  return (
    <div className="test-column">
      <div className={`test-column-header ${headerClass}`}>
        <span className="col-title">{title}</span>
        <span className={`col-count ${badge}`}>{tests?.length || 0}</span>
      </div>
      <div className="test-column-body">
        {tests && tests.length > 0 ? (
          tests.map((t, i) => (
            <div key={i} className="test-card">
              <div className="test-card-top">
                <span className="test-index">{String(i + 1).padStart(2, '0')}</span>
                <span className="test-title">{t.title}</span>
              </div>
              <p className="test-desc">{t.description}</p>
              <div className="test-card-footer">
                <span className={`status-chip ${getStatusClass(t.expectedStatus)}`}>
                  {t.expectedStatus}
                </span>
              </div>
            </div>
          ))
        ) : (
          <p className="empty-msg">No test cases.</p>
        )}
      </div>
    </div>
  )
}

/* ── Status chip colour helper ───────────────────────────────── */
function getStatusClass(status) {
  if (!status) return 'status-default'
  const s = String(status)
  if (s.startsWith('2')) return 'status-2xx'
  if (s.startsWith('4')) return 'status-4xx'
  if (s.startsWith('5')) return 'status-5xx'
  return 'status-default'
}

export default ResultSection
