import React from 'react'
import './ResultSection.css'

/**
 * ResultSection Component
 *
 * Displays the AI-generated test cases returned from the Spring Boot backend.
 * It renders the data in clearly organized sections:
 * - API Summary
 * - Positive Test Cases
 * - Negative Test Cases
 * - Validation Test Cases
 * - Expected HTTP Responses
 *
 * Also provides a "Download TestCases.txt" button that creates the file
 * entirely in the browser using the Blob API — no backend call needed.
 *
 * Props:
 * - data: TestCaseResponse object from the backend
 * - requestInfo: { method, endpoint } — shown in the download file header
 */
function ResultSection({ data, requestInfo }) {
  if (!data) return null

  /**
   * Generates a plain text representation of all test cases and triggers download.
   * Uses the browser's Blob API to create a file in memory and download it.
   */
  const handleDownload = () => {
    const lines = []
    const divider = '='.repeat(60)
    const smallDivider = '-'.repeat(40)

    lines.push('TESTPILOT AI – GENERATED TEST CASES')
    lines.push(divider)
    lines.push(`API: ${requestInfo.method.toUpperCase()} ${requestInfo.endpoint}`)
    lines.push(`Generated: ${new Date().toLocaleString()}`)
    lines.push('')

    lines.push('SUMMARY')
    lines.push(smallDivider)
    lines.push(data.summary || 'N/A')
    lines.push('')

    // Helper to format a test case array into text
    const formatTests = (tests, sectionTitle) => {
      lines.push(sectionTitle)
      lines.push(smallDivider)
      if (!tests || tests.length === 0) {
        lines.push('No test cases generated.')
      } else {
        tests.forEach((test, i) => {
          lines.push(`${i + 1}. ${test.title}`)
          lines.push(`   Description: ${test.description}`)
          lines.push(`   Expected Status: ${test.expectedStatus}`)
          lines.push('')
        })
      }
    }

    formatTests(data.positiveTests, 'POSITIVE TEST CASES')
    formatTests(data.negativeTests, 'NEGATIVE TEST CASES')
    formatTests(data.validationTests, 'VALIDATION TEST CASES')

    lines.push('EXPECTED HTTP RESPONSES')
    lines.push(smallDivider)
    if (data.expectedResponses && data.expectedResponses.length > 0) {
      data.expectedResponses.forEach((r) => {
        lines.push(`${r.status}: ${r.message}`)
      })
    } else {
      lines.push('No expected responses listed.')
    }

    lines.push('')
    lines.push(divider)
    lines.push('Generated by TestPilot AI – https://github.com/your-username/testpilot-ai')

    // Create a Blob (in-memory file) and trigger browser download
    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = 'TestCases.txt'
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <div className="result-section" id="results">

      {/* ── Result Header ──────────────────────────────────────────── */}
      <div className="result-header">
        <div className="result-header-left">
          <span className="result-status-dot" aria-hidden="true"></span>
          <h2 className="result-title">Test Cases Generated</h2>
        </div>
        <button
          id="download-btn"
          className="download-btn"
          onClick={handleDownload}
          title="Download all test cases as a .txt file"
        >
          <span aria-hidden="true">↓</span>
          Download TestCases.txt
        </button>
      </div>

      {/* ── API Summary ────────────────────────────────────────────── */}
      <div className="result-card summary-card">
        <div className="card-header">
          <span className="card-icon summary-icon" aria-hidden="true">◈</span>
          <h3 className="card-title">API Summary</h3>
        </div>
        <p className="summary-text">{data.summary}</p>
      </div>

      {/* ── Test Case Grid ─────────────────────────────────────────── */}
      <div className="test-grid">
        <TestCaseCard
          title="Positive Tests"
          icon="✓"
          iconClass="icon-positive"
          tests={data.positiveTests}
          badgeClass="badge-positive"
        />
        <TestCaseCard
          title="Negative Tests"
          icon="✗"
          iconClass="icon-negative"
          tests={data.negativeTests}
          badgeClass="badge-negative"
        />
        <TestCaseCard
          title="Validation Tests"
          icon="◉"
          iconClass="icon-validation"
          tests={data.validationTests}
          badgeClass="badge-validation"
        />
      </div>

      {/* ── Expected HTTP Responses ────────────────────────────────── */}
      <div className="result-card">
        <div className="card-header">
          <span className="card-icon icon-responses" aria-hidden="true">⇄</span>
          <h3 className="card-title">Expected HTTP Responses</h3>
          <span className="count-badge">{data.expectedResponses?.length || 0}</span>
        </div>
        <div className="responses-list">
          {data.expectedResponses && data.expectedResponses.length > 0 ? (
            data.expectedResponses.map((resp, index) => (
              <div key={index} className="response-row">
                <span className={`status-chip ${getStatusClass(resp.status)}`}>
                  {resp.status}
                </span>
                <span className="response-message">{resp.message}</span>
              </div>
            ))
          ) : (
            <p className="empty-state">No expected responses listed.</p>
          )}
        </div>
      </div>

    </div>
  )
}

/**
 * TestCaseCard — sub-component to render a single category of test cases
 */
function TestCaseCard({ title, icon, iconClass, tests, badgeClass }) {
  return (
    <div className="result-card test-case-card">
      <div className="card-header">
        <span className={`card-icon ${iconClass}`} aria-hidden="true">{icon}</span>
        <h3 className="card-title">{title}</h3>
        <span className={`count-badge ${badgeClass}`}>{tests?.length || 0}</span>
      </div>
      <div className="test-list">
        {tests && tests.length > 0 ? (
          tests.map((test, index) => (
            <div key={index} className="test-item">
              <div className="test-item-header">
                <span className="test-number">{String(index + 1).padStart(2, '0')}</span>
                <span className="test-title">{test.title}</span>
              </div>
              <p className="test-description">{test.description}</p>
              <div className="test-footer">
                <span className={`status-chip ${getStatusClass(test.expectedStatus)}`}>
                  {test.expectedStatus}
                </span>
              </div>
            </div>
          ))
        ) : (
          <p className="empty-state">No test cases generated.</p>
        )}
      </div>
    </div>
  )
}

/**
 * Returns a CSS class based on the HTTP status code for color coding.
 * 2xx = green, 4xx = orange, 5xx = red, else = default
 */
function getStatusClass(status) {
  if (!status) return 'status-default'
  const s = String(status)
  if (s.startsWith('2')) return 'status-2xx'
  if (s.startsWith('4')) return 'status-4xx'
  if (s.startsWith('5')) return 'status-5xx'
  return 'status-default'
}

export default ResultSection
